apiVersion : apps/v1
kind: Deployment
metadata:
  name: swapp-deploy-prod
  labels:
    app : swapp-deploy-prod
spec:
  selector:
    matchLabels:
      project: swapp-prod
  template:
    metadata:
      labels:
        project: swapp-prod   # Service looks for this label
    spec:
      containers:
        - name : swapp-prod
          image: dobarden/swapp-prod:prod_latest_image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: DB_HOST
            value: "prod_db_host"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "prod_db_user"
          - name: DB_PASSWORD
            value: "prod_db_pass"
          - name: DB_NAME
            value: "prod_db_name"
          resources:
            requests:
              memory: 1000Mi
              cpu: 200m

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: swapp-prod-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: swapp-deploy-prod
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: swapp-prod-service
  labels:
     env  : prod
     owner: DenisZ
spec:
  type: ClusterIP
  selector:
    project: swapp-prod
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Service
      targetPort: 8080  # Port on Pod
